// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../../../../../../../app/akun/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/akun">> = Specific
  const handler = {} as typeof import("../../../../../../../../../app/akun/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../../app/demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo">> = Specific
  const handler = {} as typeof import("../../../../../../../../../app/demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../../app/masuk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/masuk">> = Specific
  const handler = {} as typeof import("../../../../../../../../../app/masuk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../../app/model/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/model">> = Specific
  const handler = {} as typeof import("../../../../../../../../../app/model/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../../../../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../../app/sites/[siteId]/[kategori]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sites/[siteId]/[kategori]">> = Specific
  const handler = {} as typeof import("../../../../../../../../../app/sites/[siteId]/[kategori]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../../app/sites/[siteId]/lighthouse/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sites/[siteId]/lighthouse">> = Specific
  const handler = {} as typeof import("../../../../../../../../../app/sites/[siteId]/lighthouse/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../../app/sites/[siteId]/pengaturan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sites/[siteId]/pengaturan">> = Specific
  const handler = {} as typeof import("../../../../../../../../../app/sites/[siteId]/pengaturan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../../app/auth/google/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/google/callback">> = Specific
  const handler = {} as typeof import("../../../../../../../../../app/auth/google/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../../app/auth/google/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/google">> = Specific
  const handler = {} as typeof import("../../../../../../../../../app/auth/google/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../../app/keluar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/keluar">> = Specific
  const handler = {} as typeof import("../../../../../../../../../app/keluar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../../app/sites/[siteId]/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/sites/[siteId]/export">> = Specific
  const handler = {} as typeof import("../../../../../../../../../app/sites/[siteId]/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../../../../../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../../../../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../../app/sites/[siteId]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/sites/[siteId]">> = Specific
  const handler = {} as typeof import("../../../../../../../../../app/sites/[siteId]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
